Major revision.
Remove vendor (i.e., SBIA by default) from namespaces, only the package/project name matters. Add project template version 1.5 with revised doc/CMakeLists.txt configuration. Add further options to basis_project() to specify AUTHORS, COPYRIGHT, LICENSE, and CONTACT. These values are used as defaults for the BASIS Utilities functions print_contact() and print_version() as well as the generated documentation. Modify basis_add_doc() subfunctions such that INSTALL_<target>_DIR overwrites the default destination specified in the CMakeLists.txt file.

git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@2717 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/basis.sh.in b/src/utilities/bash/basis.sh.in
--- a/src/utilities/bash/basis.sh.in
+++ b/src/utilities/bash/basis.sh.in
@@ -3,7 +3,7 @@
 # @brief BASIS utilities of @PROJECT_NAME@ package.
 #
 # @note The basis.sh module was automatically created by BASIS from the
-#       template file basis.sh.in which is part of the BASIS installation.
+#       template file basis.sh.in which is part of BASIS.
 #
 # This module sources the modules of the project-independent BASIS Bash Utilities
 # which are part of the BASIS installation. Hence, it is sufficient to only
@@ -23,8 +23,8 @@
 # @ingroup BasisBashUtilities
 ##############################################################################
 
-[ "${_@PROJECT_PACKAGE_VENDOR_U@_@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED}" == 'true' ] || {
-_@PROJECT_PACKAGE_VENDOR_U@_@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED='true'
+[ "${_@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED}" == 'true' ] || {
+_@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED='true'
 
 
 # ============================================================================
@@ -40,17 +40,23 @@ _@PROJECT_PACKAGE_VENDOR_U@_@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED='true'
 
 
 ## @brief Project name.
-readonly PROJECT="@PROJECT_NAME@"
+readonly PROJECT='@PROJECT_NAME@'
 ## @brief Project version.
-readonly VERSION="@PROJECT_VERSION@"
+readonly VERSION='@PROJECT_VERSION@'
 ## @brief Major project version.
-readonly VERSION_MAJOR="@PROJECT_VERSION_MAJOR@"
+readonly VERSION_MAJOR='@PROJECT_VERSION_MAJOR@'
 ## @brief Minor project version.
-readonly VERSION_MINOR="@PROJECT_VERSION_MINOR@"
+readonly VERSION_MINOR='@PROJECT_VERSION_MINOR@'
 ## @brief Project patch number.
-readonly VERSION_PATCH="@PROJECT_VERSION_PATCH@"
+readonly VERSION_PATCH='@PROJECT_VERSION_PATCH@'
 ## @brief Project release.
-readonly RELEASE="@PROJECT_RELEASE@"
+readonly RELEASE='@PROJECT_RELEASE@'
+## @brief Default copyright of executables.
+readonly COPYRIGHT='@PROJECT_COPYRIGHT@'
+## @brief Default license of executables.
+readonly LICENSE='@PROJECT_LICENSE@'
+## @brief Default contact to use for help output of executables.
+readonly CONTACT='@PROJECT_CONTACT@'
 
 
 ## @}
@@ -64,9 +70,9 @@ readonly _BASIS_DIR="`cd -P -- \`dirname -- "${BASH_SOURCE}"\` && pwd`"
 # ============================================================================
 
 # source project-independent utiltiy functions
-. "${_BASIS_DIR}/@_BASIS_BASH_LIBRARY_DIR@/sbia/basis/utilities.sh"
+. "${_BASIS_DIR}/@_BASIS_BASH_LIBRARY_DIR@/basis/utilities.sh"
 if [[ $? -ne 0 ]]; then
-    echo "Failed to import sbia.basis.utilities module!" 1>&2
+    echo "Failed to import basis.utilities module!" 1>&2
     exit 1
 fi
 
@@ -113,4 +119,4 @@ if [ "${basis_use_executable_aliases}" == 'true' ]; then
 fi
 
 
-} # _@PROJECT_NAMESPACE_BASH@_@NAMESPACE_UPPER@_INCLUDED
+} # _@PROJECT_PACKAGE_U@_@PROJECT_NAME_U@_INCLUDED
