Use absolute paths to Bash or Python "basis.utilities" module if BASIS is not part of installation. Further, allow user to specify path using the BASIS_BASHPATH or BASIS_PYTHONPATH environment variables explicitly.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@3113 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/basis.sh.in b/src/utilities/bash/basis.sh.in
--- a/src/utilities/bash/basis.sh.in
+++ b/src/utilities/bash/basis.sh.in
@@ -71,13 +71,24 @@ CONTACT='@PROJECT_CONTACT@'
 
 readonly _BASIS_TARGET_UID_PREFIX='@PROJECT_NAMESPACE_CMAKE@'
 readonly _BASIS_EXECUTABLE_TARGETS_BASE="`cd -P -- \`dirname -- "${BASH_SOURCE}"\` && pwd`"
+_BASIS_BASH_LIBRARY_DIR='@_BASIS_BASH_LIBRARY_DIR@'
+if [ "${_BASIS_BASH_LIBRARY_DIR:0:1}" != '/' ]; then
+    _BASIS_BASH_LIBRARY_DIR="${_BASIS_EXECUTABLE_TARGETS_BASE}/${_BASIS_BASH_LIBRARY_DIR}"
+fi
+readonly _BASIS_BASH_LIBRARY_DIR
 
 # ============================================================================
 # source implementations of utility functions
 # ============================================================================
 
 # source project-independent utility functions
-. "${_BASIS_EXECUTABLE_TARGETS_BASE}/@_BASIS_BASH_LIBRARY_DIR@/basis/utilities.sh"
+[ -n "${BASIS_BASHPATH}" ] || BASIS_BASHPATH="${_BASIS_BASH_LIBRARY_DIR}"
+if [ ! -f "${BASIS_BASHPATH}/basis/utilities.sh" ]; then
+    echo "Module basis.utilities not found at ${BASIS_BASHPATH}!" 1>&2
+    echo "Specify path using the BASIS_BASHPATH environment variable." 1>&2
+    exit 1
+fi
+. "${BASIS_BASHPATH}/basis/utilities.sh"
 if [[ $? -ne 0 ]]; then
     echo "Failed to import basis.utilities module!" 1>&2
     exit 1
