Made error message more helpful.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@1354 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/executabletargetinfo.sh.in b/src/utilities/bash/executabletargetinfo.sh.in
--- a/src/utilities/bash/executabletargetinfo.sh.in
+++ b/src/utilities/bash/executabletargetinfo.sh.in
@@ -224,7 +224,7 @@ function _executabletargetinfo_sanitize
     [ -z "$2" ] && upvar $1 ''
     local sane="`echo -n "$2" | tr [:space:] '_' | tr -c [:alpha:] '_'`"
     [ -n "${sane}" ] || {
-        echo "_executabletargetinfo_sanitize(): Failed to sanitize string" 1>&2
+        echo "_executabletargetinfo_sanitize(): Failed to sanitize string '$2'" 1>&2
         exit 1
     }
     local "$1" && upvar $1 "${sane}"
