Change BASH implementation of ExecutableTargetInfo module to allow digits in target names. Further, give more explanatory error message if a key in the target info map already exists.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@2202 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/executabletargetinfo.sh.in b/src/utilities/bash/executabletargetinfo.sh.in
--- a/src/utilities/bash/executabletargetinfo.sh.in
+++ b/src/utilities/bash/executabletargetinfo.sh.in
@@ -234,7 +234,7 @@ function _executabletargetinfo_sanitize
         upvar $1 ''
         return 0
     }
-    local sane="`echo -n "$2" | tr [:space:] '_' | tr -c [:alpha:] '_'`"
+    local sane="`echo -n "$2" | tr [:space:] '_' | tr -c [:alnum:] '_'`"
     [ -n "${sane}" ] || {
         echo "_executabletargetinfo_sanitize(): Failed to sanitize string '$2'" 1>&2
         exit 1
@@ -269,6 +269,11 @@ function _executabletargetinfo_add
         exit 1
     }
     eval "readonly __EXECUTABLETARGETINFO_${name}_${key}='$3'"
+    if [ $? -ne 0 ]; then
+        echo "Failed to add ${name} of key ${key} to executable target info map!" 1>&2
+        echo "This may be caused by two CMake build target names being converted to the same key." 1>&2
+        exit 1
+    fi
 }
 
 # ----------------------------------------------------------------------------
