Use -c option instead of -C for tr as -C is not recognized by GNU version of this command.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@908 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/ExecutableTargetInfo.sh.in b/src/utilities/bash/ExecutableTargetInfo.sh.in
--- a/src/utilities/bash/ExecutableTargetInfo.sh.in
+++ b/src/utilities/bash/ExecutableTargetInfo.sh.in
@@ -198,7 +198,14 @@ get_executable_path ()
 # @retval 1 On failure.
 _executabletargetinfo_sanitize ()
 {
-    local "$1" && upvar $1 "$(echo -n "$2" | tr [:space:] '_' | tr -C [:alpha:] '_')"
+    [ $# -eq 2 ] || return 1
+    [ -z "$2" ] && upvar $1 ''
+    local sane="$(echo -n "$2" | tr [:space:] '_' | tr -c [:alpha:] '_')"
+    [ -n "${sane}" ] || {
+        echo "_executabletargetinfo_sanitize(): Failed to sanitize string" 1>&2
+        exit 1
+    }
+    local "$1" && upvar $1 "${sane}"
 }
 
 ##############################################################################
