Added Perl implementation of execute_process() function. Added further tests for execute_process() implementations. Fixed use of 'from .<pkg> import *' in Python packages.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@999 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/utilities/bash/stdaux.sh.in b/src/utilities/bash/stdaux.sh.in
--- a/src/utilities/bash/stdaux.sh.in
+++ b/src/utilities/bash/stdaux.sh.in
@@ -115,36 +115,34 @@ function execute_process
     local simulate="${4:-1}"
     local status=0
     # extract command from command-line
-    match "$args" "[ ]*('([^']|\\\')*'|\"([^\"]|\\\\\")*\"|[^ ]*)(.*)"
+    match "$args" "^[ ]*('([^']|\\\')*[^\\]'|\"([^\"]|\\\\\")*[^\\]\"|[^ ]+)(.*)$"
     [ $? -eq 0 ] || return 1
     local command=${BASH_REMATCH[1]}
     local arguments=${BASH_REMATCH[4]}
     # map build target name to file
     local exec_path && get_executable_path exec_path "${command}"
     if [ -z "${exec_path}" ]; then
-        echo "${command}: Either unknown build target or command not found"
-        [ ${allow_fail} -eq 0 ] || exit 1
-        return 1
+        echo "${command}: Either unknown build target or command not found" 1>&2
+        exit 1
     fi
     # if path contains a whitespace character...
     if match "${exec_path}" '[ \t\n]'; then
         # ...quote path with quotes inside path escaped
-        exec_path="\"`echo "${exec_path}" | sed "s/\"/\\\\\\\"/g"`\""
+        exec_path=`echo "${exec_path}" | sed 's/"/\\"/g'`
+        exec_path="\"${exec_path}\""
     fi
     # prepend absolute path of found executable
     args="${exec_path}${arguments}"
     # some verbose output
-    if [ ${verbose} -gt 0 -o ${simulate} -eq 0 ]; then
-        echo -n "> ${args}"
-        [ ${simulate} -eq 0 ] && echo -n " (simulated)"
-        echo
+    if [ ${verbose} -gt 0 ]; then
+        echo "\$> ${args}"
     fi
     # execute command
     [ ${simulate} -eq 0 ] || eval "${args}"
     status=$?
     # if command failed, exit
-    [ ${status} -eq 0 ] || {
-        echo "Subprocess ${args} failed" 1>&2
+    [ ${status} -eq 0 -o ${allow_fail} -eq 0 ] || {
+        echo "Command ${args} failed" 1>&2
         exit 1
     }
     # return exit code
