Fixed error code handling in utilities test script.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@880 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/test/utilities/test_utilities.sh.in b/test/utilities/test_utilities.sh.in
--- a/test/utilities/test_utilities.sh.in
+++ b/test/utilities/test_utilities.sh.in
@@ -42,9 +42,10 @@ run ()
         echo "\$> $@"
     fi
     "$@"
-    if [ $? -ne 0 ] ; then
-        local errcode=$?
+    local errcode=$?
+    if [ ${errcode} -ne 0 ] ; then
         echo "Failed to run command $@" 1>&2
+        echo "Error code: ${errcode}"
         exit ${errcode}
     fi
 }
