Added *.t as extension for Perl scripts (implementing tests). Added Basis.pm module for Perl. Added --language option to basisproject command. Added first test for ExecutableTargetInfo Perl module.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@884 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/test/tools/test_basisproject.sh.in b/test/tools/test_basisproject.sh.in
--- a/test/tools/test_basisproject.sh.in
+++ b/test/tools/test_basisproject.sh.in
@@ -22,6 +22,7 @@ source_dir='@TESTING_OUTPUT_DIR@/test_basisproject-source'
 binary_dir='@TESTING_OUTPUT_DIR@/test_basisproject-build'
 
 get_executable_path basisproject_path 'basis::basisproject.sh'
+[ -z "${basisproject_path}" ] && { echo "FAILED to get path of basisproject command!"; exit 1; }
 
 # ============================================================================
 # options
@@ -159,11 +160,10 @@ cleanup ()
 test_minimal_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_minimal_empty_project():"
+    echo "test_minimal_empty_project:"
     echo
     create --minimal
     build
-    cleanup
     echo
     echo "SUCCESS"
 }
@@ -173,11 +173,10 @@ test_minimal_empty_project ()
 test_standard_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_standard_empty_project():"
+    echo "test_standard_empty_project:"
     echo
     create --standard
     build
-    cleanup
     echo
     echo "SUCCESS"
 }
@@ -187,11 +186,10 @@ test_standard_empty_project ()
 test_full_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_full_empty_project():"
+    echo "test_full_empty_project:"
     echo
     create --full
     build
-    cleanup
     echo
     echo "SUCCESS"
 }
@@ -201,12 +199,11 @@ test_full_empty_project ()
 test_minimal_to_standard_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_minimal_to_standard_empty_project():"
+    echo "test_minimal_to_standard_empty_project:"
     echo
     create --minimal
     update --standard
     build
-    cleanup
     echo
     echo "SUCCESS"
 }
@@ -216,12 +213,11 @@ test_minimal_to_standard_empty_project ()
 test_minimal_to_full_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_minimal_to_full_empty_project():"
+    echo "test_minimal_to_full_empty_project:"
     echo
     create --minimal
     update --full
     build
-    cleanup
     echo
     echo "SUCCESS"
 }
@@ -231,13 +227,39 @@ test_minimal_to_full_empty_project ()
 test_full_to_minimal_empty_project ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_full_to_minimal_empty_project():"
+    echo "test_full_to_minimal_empty_project:"
     echo
     create --full
     update_error --minimal # fails because CTestConfig.cmake was modified during creation
     update --minimal --force
     build
-    cleanup
+    echo
+    echo "SUCCESS"
+}
+
+##############################################################################
+# @brief Test configuration of used languages.
+test_configuration_of_language_support ()
+{
+    local line
+
+    echo "------------------------------------------------------------------------------"
+    echo "test_configuration_of_language_support:"
+    echo
+    create --minimal --language CXX
+    line="$(grep 'LANGUAGES' "${source_dir}/CMakeLists.txt")"
+    if [[ "${line}" != '  LANGUAGES   CXX #AddLanguageHere' ]]; then
+        echo
+        echo "FAILED"
+        exit 1
+    fi
+    update --language python --language Perl
+    line="$(grep 'LANGUAGES' "${source_dir}/CMakeLists.txt")"
+    if [[ "${line}" != '  LANGUAGES   CXX python Perl #AddLanguageHere' ]]; then
+        echo
+        echo "FAILED"
+        exit 1
+    fi
     echo
     echo "SUCCESS"
 }
@@ -251,7 +273,7 @@ test_full_to_minimal_empty_project ()
 test_required_arguments ()
 {
     echo "------------------------------------------------------------------------------"
-    echo "test_required_arguments():"
+    echo "test_required_arguments:"
     echo
     runerr "${basisproject_path}"
     runerr "${basisproject_path}" --name 'TestProject'
@@ -273,6 +295,10 @@ test_full_empty_project
 test_minimal_to_standard_empty_project
 test_minimal_to_full_empty_project
 test_full_to_minimal_empty_project
+test_configuration_of_language_support
 
 # negative tests
 test_required_arguments
+
+# clean up
+cleanup
diff --git a/test/utilities/test_utilities.sh.in b/test/utilities/test_utilities.sh.in
--- a/test/utilities/test_utilities.sh.in
+++ b/test/utilities/test_utilities.sh.in
@@ -25,6 +25,11 @@ ressources_dir='@TESTING_DIR@/ressources/test_utilities'
 source_dir='@TESTING_OUTPUT_DIR@/test_utilities-source'
 binary_dir='@TESTING_OUTPUT_DIR@/test_utilities-build'
 
+get_executable_path basisproject_path 'basis::basisproject.sh'
+[ -z "${basisproject_path}" ] && { echo "FAILED to get path of basisproject command!"; exit 1; }
+
+readonly cwd="$(pwd)"
+
 # ============================================================================
 # options
 # ============================================================================
@@ -75,6 +80,41 @@ runerr ()
 }
 
 ##############################################################################
+# @brief Creates a project using the basisproject command-line tool.
+create ()
+{
+    echo "Creating test project..."
+    [ -d "${source_dir}" ] && run rm -rf "${source_dir}"
+    run "${basisproject_path}" --name 'TestUtilities' \
+        --description "A project used to test the BASIS utilities." \
+        --root "${source_dir}" \
+        --language CXX \
+        --language Java \
+        --language Python \
+        --language Perl \
+        --language BASH \
+        --language MATLAB
+    echo "Creating test project... - done"
+}
+
+##############################################################################
+# @brief Tries to build a project created by basisproject.
+build ()
+{
+    echo "Configuring test project..."
+    [ -d "${binary_dir}" ] && run rm -rf "${binary_dir}"
+    run mkdir -p "${binary_dir}"
+    run cd "${binary_dir}"
+    run cmake "-DBASIS_DIR=${basis_dir}" "${source_dir}"
+    echo "Configuring test project... - done"
+    echo "Building test project..."
+    run make
+    echo "Building test project... - done"
+
+    run cd "${cwd}"
+}
+
+##############################################################################
 # @brief Copy file from ressources directory to project source tree.
 #
 # @param [in] file   File path relative to top directory of ressources tree.
@@ -93,33 +133,12 @@ copy ()
 }
 
 ##############################################################################
-# @brief Creates a project using the basisproject command-line tool.
-create ()
+# @brief Add test to test project.
+add_test ()
 {
-    echo "Creating test project..."
-    [ -d "${source_dir}" ] && run rm -rf "${source_dir}"
-    run "${basisproject_path}" --name 'TestUtilities' --description "A project used to test the BASIS utilities." --root "${source_dir}" "$@"
-    echo "Creating test project... - done"
-}
-
-##############################################################################
-# @brief Tries to build a project created by basisproject.
-build ()
-{
-    local cwd="$(pwd)"
-    readonly cwd
-
-    echo "Configuring test project..."
-    [ -d "${binary_dir}" ] && run rm -rf "${binary_dir}"
-    run mkdir -p "${binary_dir}"
-    run cd "${binary_dir}"
-    run cmake "-DBASIS_DIR=${basis_dir}" "${source_dir}"
-    echo "Configuring test project... - done"
-    echo "Building test project..."
-    run make
-    echo "Building test project... - done"
-
-    run cd "${cwd}"
+    local impl=$1
+    copy ${impl} 'test'
+    echo "basis_add_test (\"${impl}\")" >> "${source_dir}/test/CMakeLists.txt"
 }
 
 ##############################################################################
@@ -131,18 +150,20 @@ cleanup ()
 }
 
 # ============================================================================
-# tests
-# ============================================================================
-
-# ============================================================================
 # main
 # ============================================================================
 
-# build tests
 create
+add_test 'test_ExecutableTargetInfo.t.in'
 build
-
-# run tests
-
-# clean up
-cleanup
+run cd "${binary_dir}"
+if [ ${FLAGS_verbose} -gt 1 ]; then
+    run ctest -V -V
+elif [ ${FLAGS_verbose} -gt 0 ]; then
+    run ctest -V
+else
+    run ctest
+fi
+cd "${cwd}"
+#cleanup
+exit 0
