Fixed ExecutableTargetInfo module for BASH. Initialization in subshell had no effect on caller. Renamed utilities library from libbasis-utils to libbasis-utilities. Separated configuration of auxiliary modules for scripting languages from configuration of ExecutableTargetInfo modules. Add Basis.sh module for BASH. Moved include file basis.h from 'include' directory to 'src/utilities/cxx'. This file is configured for each project separately. Consider the BASIS utilities library to be fused with the project's implementation rather than an external library. Added simple test for basisproject command-line tool.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@883 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/tools/basisproject.sh.in b/src/tools/basisproject.sh.in
--- a/src/tools/basisproject.sh.in
+++ b/src/tools/basisproject.sh.in
@@ -18,11 +18,9 @@
 # settings
 # ============================================================================
 
-## @brief Canonical path of directory where executable is located.
-exec_dir=$(get_executable_directory)
-
-## @brief Name of this executable.
-exec_name=$(get_executable_name)
+# executable information
+get_executable_directory exec_dir
+get_executable_name      exec_name
 
 ## @brief Name of CMake configuration file used to resolve dependencies.
 depends_file='Depends.cmake'
@@ -44,10 +42,10 @@ cache=".basis/cache"
 print_options ()
 {
     echo "Required Options:"
-    echo "  <project name>             Name of the new project."
-    echo "  -d [ --description ] arg   Brief project description. Option not allowed when modifying"
+    echo "  --name, -n <Project>       Name of the new project."
+    echo "  --description, -d <arg>    Brief project description. Option not allowed when modifying"
     echo "                             an existent project."
-    echo "  -r [ --root ] arg          Specify root directory of new project or directory of"
+    echo "  --root, -r <arg>           Specify root directory of new project or directory of"
     echo "                             existing project. If the specified directory already exists"
     echo "                             this program will modify this project. The project name and"
     echo "                             description options must not be given in this case as these"
@@ -60,69 +58,55 @@ print_options ()
     echo
     echo "                               --example"
     echo "                               --system-tests"
-    echo "                               --no-conf-components"
-    echo "                               --no-conf-depends"
-    echo "                               --no-conf-find"
-    echo "                               --no-conf-generate"
-    echo "                               --no-conf-package"
-    echo "                               --no-conf-script"
-    echo "                               --no-conf-settings"
-    echo "                               --no-conf-use"
-    echo "                               --no-conf-version"
-    echo "                               --no-data"
-    echo "                               --no-unit-tests"
+    echo "                               --noconf-components"
+    echo "                               --noconf-depends"
+    echo "                               --noconf-find"
+    echo "                               --noconf-generate"
+    echo "                               --noconf-package"
+    echo "                               --noconf-script"
+    echo "                               --noconf-settings"
+    echo "                               --noconf-use"
+    echo "                               --noconf-version"
+    echo "                               --nodata"
+    echo "                               --nounit-tests"
     echo
     echo "  --full                     Choose full project template. Corresponds to selecting all files."
     echo
-    echo "  --conf-components          Whether to include custom Components.cmake file."
-    echo "  --conf-depends             Whether to include custom Depends.cmake file."
-    echo "  --conf-find                Whether to include custom <project>Config.cmake file."
-    echo "  --conf-find-version        Whether to include custom <project>ConfigVersion.cmake file."
-    echo "  --conf-generate            Whether to include custom GenerateConfig.cmake script."
-    echo "  --conf-package             Whether to include custom Package.cmake file."
-    echo "  --conf-script              Whether to include custom ScriptConfig.cmake file."
-    echo "  --conf-settings            Whether to include custom Settings.cmake file."
-    echo "  --conf-test                Whether to include custom CTestCustom.cmake file."
-    echo "  --conf-use                 Whether to include custom <project>Use.cmake file."
-    echo "  --data                     Whether to include support of auxiliary data files."
-    echo "  --example                  Whether to include support of example."
-    echo "  --test                     Whether to include support for testing."
+    echo "  --[no]conf-components      Whether to include custom Components.cmake file."
+    echo "  --[no]conf-depends         Whether to include custom Depends.cmake file."
+    echo "  --[no]conf-find            Whether to include custom <Project>Config.cmake file."
+    echo "  --[no]conf-find-version    Whether to include custom <Project>ConfigVersion.cmake file."
+    echo "  --[no]conf-generate        Whether to include custom GenerateConfig.cmake script."
+    echo "  --[no]conf-package         Whether to include custom Package.cmake file."
+    echo "  --[no]conf-script          Whether to include custom ScriptConfig.cmake.in file."
+    echo "  --[no]conf-settings        Whether to include custom Settings.cmake file."
+    echo "  --[no]conf-test            Whether to include custom CTestCustom.cmake file."
+    echo "  --[no]conf-use             Whether to include custom <Project>Use.cmake file."
+    echo "  --[no]data                 Whether to include support of auxiliary data files."
+    echo "  --[no]example              Whether to include support of example."
+    echo "  --[no]test                 Whether to include support for testing."
     echo
-    echo "  --no-conf-components       Whether to exclude custom Components.cmake file."
-    echo "  --no-conf-depends          Whether to exclude custom Depends.cmake file."
-    echo "  --no-conf-find             Whether to exclude custom <project>Config.cmake file."
-    echo "  --no-conf-find-version     Whether to exclude custom <project>ConfigVersion.cmake file."
-    echo "  --no-conf-generate         Whether to exclude custom GenerateConfig.cmake script."
-    echo "  --no-conf-package          Whether to exclude custom Package.cmake file."
-    echo "  --no-conf-script           Whether to exclude custom ScriptConfig.cmake file."
-    echo "  --no-conf-settings         Whether to exclude custom Settings.cmake file."
-    echo "  --no-conf-test             Whether to exclude custom CTestCustom.cmake file."
-    echo "  --no-conf-use              Whether to exclude custom <project>Use.cmake file."
-    echo "  --no-data                  Whether to exclude support of auxiliary data files."
-    echo "  --no-example               Whether to exclude support of example."
-    echo "  --no-test                  Whether to exclude support for testing (implies --no-conf-test)."
-    echo
-    echo "  -p [ --pkg ] arg           Name of external package required by this project."
-    echo "  --optPkg arg               Name of external package optionally used by this project."
+    echo "  --use <arg>                Name of external package used by this project."
+    echo "  --optuse <arg>             Name of external package optionally used by this project."
     echo
     echo "Options:"
     echo "  --clean                    Remove backup and other temporary files left behind."
     echo "  --clean-all                Remove not only backup and other temporary files, but also"
     echo "                             the hidden '.basis' directories with copies of the template files."
     echo "  --force                    Force deletion of modified template files."
-    echo "  --no-update                Do not update existing files. Only add new files."
+    echo "  --[no]update               Do not update existing files. Only add new files."
     echo "                             By default, in case of existing files, the project file is updated"
     echo "                             by merging changes of the possibly newer template and the existing file."
-    echo "  --no-backup                Do not backup project files before updating them."
+    echo "  --[no]backup               Do not backup project files before updating them."
     echo "                             By default, before any existing project file is modified,"
     echo "                             it is copied to a file with extension '~' before."
     echo "                             The creation of these backup files is disabled by this option."
-    echo "  -t [ --template ] arg      Root directory of project template."
+    echo "  --template, -t <arg>       Root directory of project template."
     echo
-    echo "  -v [ --verbose ]           Increases verbosity of output messages. Can be given multiple times."
-    echo "  -h [ --help ]              Displays help and exit."
-    echo "  -u [ --usage ]             Displays usage information and exits."
-    echo "  -V [ --version ]           Displays version information and exits."
+    echo "  --verbose, -v              Increases verbosity of output messages. Can be given multiple times."
+    echo "  --help, -h                 Displays help and exit."
+    echo "  --helpshort                Displays usage information and exits."
+    echo "  --version, -V              Displays version information and exits."
 }
 
 ##############################################################################
@@ -134,7 +118,7 @@ print_usage ()
     echo "@NAME@ (@PROJECT_NAME@)"
     echo
     echo "Usage:"
-	echo "  $exec_name [options] <project name>"
+	echo "  $exec_name [options]"
     echo
     print_options
     echo
@@ -150,7 +134,7 @@ print_help ()
     echo "@NAME@ (@PROJECT_NAME@)"
     echo
     echo "Usage:"
-	echo "  $exec_name [options] <project name>"
+	echo "  $exec_name [options]"
 	echo
 	echo "Description:"
     echo "  This command-line tool can be used to create a new BASIS project from the"
@@ -159,7 +143,7 @@ print_help ()
     echo "  Depending on the grade of customization or optional inclusion of template"
     echo "  components, different subsets of the fully featured project template can be"
     echo "  selected. Additional template files and folders can be added to an existing"
-    echo "  project at any time. Further, if the --no-* options are given explicitly,"
+    echo "  project at any time. Further, if the --no* options are given explicitly,"
     echo "  project files previously copied from the template are deleted. Files are,"
     echo "  however, only deleted if they were not modified by the project developer since"
     echo "  their creation and hence do not contain project related changes. Similarly are"
@@ -186,22 +170,22 @@ print_help ()
     echo "  find the package are added. Note that these may not work for this unsupported"
     echo "  package. In this case, the $depends_file file has to be edited manually."
     echo "  Note that if an existing project is modified, the $depends_file file is added if"
-    echo "  not yet existent, ignoring the option --no-config-depends."
+    echo "  not yet existent, ignoring the option --noconfig-depends."
     echo
 	print_options
     echo
     echo "Examples:"
-	echo "  $exec_name ProjectName -d \"Novel image analysis method.\""
+	echo "  $exec_name ProjectName --description \"Novel image analysis method.\""
     echo "    Create a new project named 'ProjectName' under the current working"
     echo "    directory using the default project template."
     echo
-	echo "  $exec_name ProjectName -d \"Novel image analysis method.\" -p VTK"
+	echo "  $exec_name ProjectName --description \"Novel image analysis method.\" --use VTK"
     echo "    Create new project with dependency on the package 'VTK'."
     echo
-    echo "  $exec_name -r path/to/existing/project --tests --conf-tests"
+    echo "  $exec_name --root path/to/existing/project --tests --conf-tests"
     echo "    Add full testing support to existing project."
     echo
-    echo "  $exec_name -r path/to/existing/porject -p ITK --optPkg Matlab"
+    echo "  $exec_name --root path/to/existing/porject --use ITK --optuse Matlab"
     echo "    Add dependencies on ITK (mandatory) and MATLAB (optional) to existing project."
     echo
     print_contact
@@ -317,7 +301,7 @@ tests=0              # add/remove testing tree
 while [ $# -gt 0 ]
 do
 	case "$1" in
-		-u|--usage)
+		--helpshort)
 			print_usage
 			exit 0
 			;;
@@ -327,7 +311,7 @@ do
 			exit 0
 			;;
 
-		-V|--version)
+		--version)
 			print_version "@NAME@"
 			exit 0
 			;;
@@ -341,42 +325,57 @@ do
             if [ $# -gt 0 ]; then
                 template=$(make_absolute $1)
             else
-                echo "Option -t requires an argument!" 1>&2
+                echo "Option --template requires an argument!" 1>&2
                 exit 1
             fi
             ;;
  
         -r|--root)
             if [ ! -z "$root" ]; then
-                echo "Option -r may only be given once!" 1>&2
+                echo "Option --root may only be given once!" 1>&2
                 exit 1
             fi
-
             shift
             if [ $# -gt 0 ]; then
                 root=$(make_absolute $1)
             else
-                echo "Option -r requires an argument!" 1>&2
+                echo "Option --root requires an argument!" 1>&2
+                exit 1
+            fi
+            ;;
+
+        -n|--name)
+            if [ ! -z "$name" ]; then
+                echo "Option --name may only be given once!" 1>&2
+                exit 1
+            fi
+            shift
+            if [ $# -gt 0 ]; then
+                name="$1"
+            else
+                echo "Option --name requires an argument!" 1>&2
                 exit 1
             fi
             ;;
 
         -d|--description)
             if [ ! -z "$description" ]; then
-                echo "Option -d may only be given once!" 1>&2
+                echo "Option --description may only be given once!" 1>&2
                 exit 1
             fi
-
             shift
             if [ $# -gt 0 ]; then
                 description="$1"
             else
-                echo "Option -d requires an argument!" 1>&2
+                echo "Option --description requires an argument!" 1>&2
                 exit 1
             fi
             ;;
 
-        --no-update)
+        --update)
+            update=1
+            ;;
+        --noupdate)
             update=0
             ;;
 
@@ -384,26 +383,26 @@ do
             force=1
             ;;
 
-        -p|--pkg)
+        --use)
             shift
             if [ $# -gt 0 ]; then
                 package_names[$package_num]="$1"
                 package_required[$package_num]=1
                 ((package_num++))
             else
-                echo "Option -p requires an argument!" 1>&2
+                echo "Option --use requires an argument!" 1>&2
                 exit 1
             fi
             ;;
 
-        --optPkg)
+        --optuse)
             shift
             if [ $# -gt 0 ]; then
                 package_names[$package_num]="$1"
                 package_required[$package_num]=0
                 ((package_num++))
             else
-                echo "Option --optPkg requires an argument!" 1>&2
+                echo "Option --optuse requires an argument!" 1>&2
                 exit 1
             fi
             ;;
@@ -459,104 +458,91 @@ do
         --conf-settings)
             conf_settings=1
             ;;
-
-        --no-conf-settings)
+        --noconf-settings)
             conf_settings=-1
             ;;
 
         --conf-depends)
             conf_depends=1
             ;;
-
-        --no-conf-depends)
+        --noconf-depends)
             conf_depends=-1
             ;;
 
         --conf-components)
             conf_components=1
             ;;
-
-        --no-conf-components)
+        --noconf-components)
             conf_components=-1
             ;;
 
         --conf-package)
             conf_package=1
             ;;
-
-        --no-conf-package)
+        --noconf-package)
             conf_package=-1
             ;;
 
         --conf-find)
             conf_find=1
             ;;
-
-        --no-conf-find)
+        --noconf-find)
             conf_find=-1
             ;;
 
         --conf-find-version)
             conf_find_version=1
             ;;
-
-        --no-conf-find-version)
+        --noconf-find-version)
             conf_find_version=-1
             ;;
 
         --conf-generate)
             conf_generate=1
             ;;
-
-        --no-conf-generate)
+        --noconf-generate)
             conf_generate=-1
             ;;
 
         --conf-script)
             conf_script=1
             ;;
-
-        --no-conf-script)
+        --noconf-script)
             conf_script=-1
             ;;
 
-        --conf-test|--conf-tests)
+        --conf-test)
             conf_tests=1
             ;;
-
-        --no-conf-test|--no-conf-tests)
+        --noconf-test)
             conf_tests=-1
             ;;
 
         --conf-use)
             conf_use=1
             ;;
-
-        --no-conf-use)
+        --noconf-use)
             conf_use=-1
             ;;
 
         --data)
             data=1
             ;;
-
-        --no-data)
+        --nodata)
             data=-1
             ;;
 
         --example)
             example=1
             ;;
-
-        --no-example)
+        --noexample)
             example=-1
             ;;
 
-        --test|--tests)
+        --test)
             tests=1
             ;;
-
-        --no-test|--no-tests)
+        --notest)
             tests=-1
             ;;
 
@@ -566,11 +552,8 @@ do
             ;;
 
         *)
-            if [ ! -z "$name" ]; then
-                echo "More than one project name specified!" 1>&2
-                exit 1
-            fi
-            name="$1"
+            echo "Invalid argument $1" 1>&2
+            exit 1
             ;;
 	esac
     shift
@@ -599,8 +582,8 @@ if [ ! -z "$name" ]; then
     fi
     if [ -e "$root" ]; then
         echo "Directory or file of name $root exists already." 1>&2
-        echo "Please choose another project name or root directory using the -r option." 1>&2
-        echo "If you want to modify an existing project, please provide the root directory using the -r option." 1>&2
+        echo "Please choose another project name or root directory using the --root option." 1>&2
+        echo "If you want to modify an existing project, please provide the root directory using the --root option." 1>&2
         exit 1
     fi
     if [ -z "$description" ]; then
@@ -617,7 +600,7 @@ elif [ ! -z "$root" ]; then
     fi
     if [ ! -z "$description" ]; then
         echo "Cannot modify description of existing project. Please edit root CMakeLists.txt file manually." 1>&2
-        echo "Do not use option -d when attempting to modify an existing project." 1>&2
+        echo "Do not use option --description when attempting to modify an existing project." 1>&2
         exit 1
     fi
     if [ -z "$name" ]; then
@@ -892,7 +875,7 @@ del ()
     # delete existing file and copy of template
     elif [ -f "$root/$path" ]; then
         # check if project file differs from template
-        diff "$root/$path" "$template/$path"
+        diff "$root/$path" "$template/$path" > /dev/null
         if [ $? -ne 0 -a $force -eq 0 ]; then
             echo "S $root/$path - file was modified; use --force to force deletion"
             return 1
diff --git a/src/utilities/bash/ExecutableTargetInfo.sh.in b/src/utilities/bash/ExecutableTargetInfo.sh.in
--- a/src/utilities/bash/ExecutableTargetInfo.sh.in
+++ b/src/utilities/bash/ExecutableTargetInfo.sh.in
@@ -21,11 +21,17 @@ __SBIA_@PROJECT_NAME_UPPER@_EXECUTABLETARGETINFO_INCLUDED=1
 # constants
 # ============================================================================
 
-## @brief Canonical path of directory containing ExecutableTargetInfo module
+## @brief Absolute directory path of ExecutableTargetInfo.sh module.
 readonly __EXECUTABLETARGETINFO_dir=@BASIS_BASH___DIR__@
 
 ## @brief Default namespace used to convert target name to target UID.
 readonly __EXECUTABLETARGETINFO_namespace='@PROJECT_NAME_LOWER@'
+
+# ============================================================================
+# modules
+# ============================================================================
+
+source "${__EXECUTABLETARGETINFO_dir}/Core.sh" # core utilities
 
 # ============================================================================
 # public functions
@@ -38,75 +44,127 @@ readonly __EXECUTABLETARGETINFO_namespace='@PROJECT_NAME_LOWER@'
 ##############################################################################
 # @brief Get UID of build target.
 #
-# @param [in] target Name/UID of build target.
+# @param [out] uid    UID of build target.
+# @param [in]  target Name/UID of build target.
 #
-# @returns UID of build target.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 get_target_uid ()
 {
-    local target=$(_executabletargetinfo_sanitize "$1")
+    [ $# -eq 2 ] || return 1
+
+    local target="$2"
+
+    # sanitize input
+    _executabletargetinfo_sanitize target "${target}"
     # initialize module if not done yet - this is only done here because
     # whenever information is looked up about an executable target, this
     # function is invoked first
     if [ -z "${__EXECUTABLETARGETINFO_initialized}" ]; then
-        _executabletargetinfo_initialize
+        _executabletargetinfo_initialize || return 1
     fi
     # convert target name to target UID
-    if [ -z $(_executabletargetinfo_get ${target} LOCATION) ] && [[ "${target//__/}" == "${target}" ]]; then
-        echo -n "${__EXECUTABLETARGETINFO_namespace}__${target}"
-    else
-        echo -n "${target}"
+    local path && _executabletargetinfo_get path "${target}" LOCATION
+    if [ -z "${path}" ] && [[ "${target//__/}" == "${target}" ]]; then
+        target="${__EXECUTABLETARGETINFO_namespace}__${target}"
     fi
+
+    local "$1" && upvar $1 "${target}"
 }
 
 ##############################################################################
 # @brief Get name of executable file.
 #
-# @param [in] target Name/UID of build target. If no argument is given,
-#                    the name of the calling executable is returned instead.
+# @param [out] name   Name of the executable or an empty string if unknown.
+# @param [in]  target Name/UID of build target. If no argument is given,
+#                     the name of the calling executable is returned instead.
 #
-# @returns The name of the executable.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 get_executable_name ()
 {
-    # if called without arguments, return name of calling executable
-    if [ $# -eq 0 ]; then
-        echo ${0##*/}
-    # otherwise, lookup name of executable corresponding to this build target
+    [ $# -eq 1 ] || [ $# -eq 2 ] || return 1
+
+    local name
+
+    # if no target name given, get name of this executable
+    if [ $# -lt 2 ]; then
+        name="${0##*/}"
+    # otherwise, get name of executable built by named target
     else
-        basename "$(get_executable_path $1)"
+        local path && get_executable_path path "$2"
+        name="$(basename "${path}")"
     fi
+
+    local "$1" && upvar $1 "${name}"
 }
 
 ##############################################################################
 # @brief Get directory of executable file.
 #
-# @param [in] target Name/UID of build target. If no argument is given,
-#                    the directory where the file of the calling executable
-#                    is located is returned.
+# @param [out] dir    Absolute directory of executable file.
+# @param [in]  target Name/UID of build target. If no argument is given,
+#                     the directory where the file of the calling executable
+#                     is located is returned.
 #
-# @returns The directory part of the executable file path.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 get_executable_directory ()
 {
-    dirname "$(get_executable_path $1)"
+    [ $# -eq 1 ] || [ $# -eq 2 ] || return 1
+
+    local path
+
+    # if no target name given, get path of this executable
+    if [ $# -lt 2 ]; then
+        get_executable_path path
+    # otherwise, get path of executable of named target
+    else
+        get_executable_path path "$2"
+    fi
+    # get directory component of path
+    local dir="$(dirname "${path}")"
+
+    local "$1" && upvar $1 "${dir}"
 }
 
 ##############################################################################
-# @brief Get canonical path of executable file.
+# @brief Get absolute path of executable file.
 #
-# @param [in] target Name/UID of build target. If no argument is given,
-#                    the file path of the calling executable is returned.
+# @param [out] path   Absolute path of executable file.
+# @param [in]  target Name/UID of build target. If no argument is given,
+#                     the file path of the calling executable is returned.
 #
-# @returns The canonical file path of the executable.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 get_executable_path ()
 {
-    # if called without arguments, return path of calling executable
-    if [ $# -eq 0 ]; then
-        realpath $0
-    # otherwise, lookup name of executable corresponding to this build target
+    [ $# -eq 1 ] || [ $# -eq 2 ] || return 1
+
+    local path
+
+    # if no target name given, get path of this executable
+    if [ $# -lt 2 ]; then
+        path="$(realpath "$0")"
+    # otherwise, get path of executable built by named target
     else
-        local uid=$(get_target_uid "$1")
-        local path=$(_executabletargetinfo_get ${uid} 'LOCATION')
-        _executabletargetinfo_to_absolute_path ${path} ${__EXECUTABLETARGETINFO_dir}
+        # get UID of target
+        local uid && get_target_uid uid "$2"
+        # get path relative to this module
+        _executabletargetinfo_get path "${uid}" LOCATION
+        # make path absolute
+        _executabletargetinfo_to_absolute_path path "${path}" "${__EXECUTABLETARGETINFO_dir}"
     fi
+
+    local "$1" && upvar $1 "${path}"
 }
 
 
@@ -120,12 +178,16 @@ get_executable_path ()
 ##############################################################################
 # @brief Sanitize string for use in variable name.
 #
-# @param [in] str String to be sanitized.
+# @param [out] out Sanitized string.
+# @param [in]  str String to be sanitized.
 #
-# @returns Sanitized string that can be used as variable name.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 _executabletargetinfo_sanitize ()
 {
-    echo -n "$1" | tr [:space:] '_' | tr -C [:alpha:] '_'
+    local "$1" && upvar $1 "$(echo -n "$2" | tr [:space:] '_' | tr -C [:alpha:] '_')"
 }
 
 ##############################################################################
@@ -140,9 +202,11 @@ _executabletargetinfo_sanitize ()
 # @returns Sets a readonly variable that represents the (key, value) entry.
 _executabletargetinfo_add ()
 {
-    local key=$(_executabletargetinfo_sanitize "$1")
-    local name=$(_executabletargetinfo_sanitize "$2")
-    eval readonly '__EXECUTABLETARGETINFO_'"${name}"'_'"${key}"='$3'
+    [ $# -eq 3 ] || return 1
+
+    local key  && _executabletargetinfo_sanitize key  "$1"
+    local name && _executabletargetinfo_sanitize name "$2"
+    eval "readonly __EXECUTABLETARGETINFO_${name}_${key}='$3'"
 }
 
 ##############################################################################
@@ -150,41 +214,55 @@ _executabletargetinfo_add ()
 #
 # @sa _executabletargetinfo_add()
 #
-# @param [in] key  Hash key.
-# @param [in] name Name of the hash table.
+# @param [out] value Value corresponding to given @p key
+#                    or an empty string if key is unknown.
+# @param [in]  key   Hash key.
+# @param [in]  name  Name of the hash table.
 #
-# @returns Value stored under the given key in the hash table or an empty
-#          string if the hash table does not exist or the key is unknown.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 _executabletargetinfo_get ()
 {
-    local key=$(_executabletargetinfo_sanitize "$1")
-    local name=$(_executabletargetinfo_sanitize "$2")
-    eval echo -n '${__EXECUTABLETARGETINFO_'"${name}"'_'"${key}"'}'
+    [ $# -eq 3 ] || return 1
+
+    local key  && _executabletargetinfo_sanitize key  "$2"
+    local name && _executabletargetinfo_sanitize name "$3"
+    eval "local value=\${__EXECUTABLETARGETINFO_${name}_${key}}"
+
+    local "$1" && upvar $1 "${value}"
 }
 
 ##############################################################################
 # @brief Make relative path absolute.
 #
-# @attention The directory referred to by the directory part of the path must exist.
+# @attention The directory component of the path must be an existent directory.
 #
 # @todo Implement this function without the use of cd such that non-existent
 #       paths can be simplified as well.
 #
-# @param [in] path Absolute or relative path.
-# @param [in] base Base path used for relative paths.
+# @param [out] simplified Simplified @p path.
+# @param [in]  path       Absolute or relative path.
+# @param [in]  base       Base path used for relative paths.
 #
-# @returns Simplified absolute path.
+# @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 _executabletargetinfo_to_absolute_path ()
 {
-    local path=$1
-    local base=${2:-$(pwd)}
-    local dir=$(dirname ${path})
+    [ $# -eq 2 ] || [ $# -eq 3 ] || return 1
+
+    local path="$2"
+    local base="$3"
+    local dir="$(dirname "${path}")"
 
     if [ -d "${base}" -a -d "${dir}" ]; then
-        echo -n $(cd ${base}; cd ${dir}; pwd)/$(basename ${path})
-    else
-        echo -n ${path}
+        path=$(cd ${base}; cd ${dir}; pwd)/$(basename ${path})
     fi
+
+    local "$1" && upvar $1 "${path}"
 }
 
 ##############################################################################
@@ -200,8 +278,29 @@ _executabletargetinfo_to_absolute_path ()
 # called first before any lookup of information.
 #
 # @returns Nothing.
+#
+# @retval 0 On success.
+# @retval 1 On failure.
 _executabletargetinfo_initialize ()
 {
+    [ $# -eq 0 ] || return 1
+
     @EXECUTABLE_TARGET_INFO@
+
     __EXECUTABLETARGETINFO_initialized=1
+    return 0
 }
+
+# ============================================================================
+# aliases (optional)
+# ============================================================================
+
+if [ -z "${basis_enable_target_aliases}" ] || [ ${basis_enable_target_aliases} -eq 0 ]; then
+    return
+fi
+
+# define aliases of build target names to executable file paths
+@EXECUTABLE_ALIASES@
+
+# enable expansion of aliases also in non-interactive shells
+shopt -s expand_aliases
diff --git a/test/utilities/test_utilities.sh.in b/test/utilities/test_utilities.sh.in
--- a/test/utilities/test_utilities.sh.in
+++ b/test/utilities/test_utilities.sh.in
@@ -21,7 +21,8 @@
 # ============================================================================
 
 basis_dir='@TESTING_BASIS_DIR@'
-source_dir='@TESTING_DIR@/ressources/test_utilities'
+ressources_dir='@TESTING_DIR@/ressources/test_utilities'
+source_dir='@TESTING_OUTPUT_DIR@/test_utilities-source'
 binary_dir='@TESTING_OUTPUT_DIR@/test_utilities-build'
 
 # ============================================================================
@@ -29,6 +30,7 @@ binary_dir='@TESTING_OUTPUT_DIR@/test_utilities-build'
 # ============================================================================
 
 FLAGS "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
 
 # ============================================================================
 # helpers
@@ -44,10 +46,88 @@ run ()
     "$@"
     local errcode=$?
     if [ ${errcode} -ne 0 ] ; then
+        echo
         echo "Failed to run command $@" 1>&2
-        echo "Error code: ${errcode}"
+        echo
+        echo "FAILED"
         exit ${errcode}
     fi
+    return 0
+}
+
+##############################################################################
+# @brief Run command with arguments where error is expected.
+runerr ()
+{
+    if [ ${FLAGS_verbose} -gt 0 ]; then
+        echo "\$> $@"
+    fi
+    "$@"
+    local errcode=$?
+    if [ ${errcode} -eq 0 ] ; then
+        echo
+        echo "Command $@ was unexpectedly successful" 1>&2
+        echo
+        echo "FAILED"
+        exit 1
+    fi
+    return 0
+}
+
+##############################################################################
+# @brief Copy file from ressources directory to project source tree.
+#
+# @param [in] file   File path relative to top directory of ressources tree.
+# @param [in] prefix Path prefix relative to project source tree. Defaults
+#                    to the root of the project source tree itself.
+# @param [in] name   Name of file in project source tree. Defaults to the
+#                    name of the file given by @p file.
+#
+# @returns Nothing.
+copy ()
+{
+    local file=$1
+    local prefix=${2:-'.'}
+    local name=${3:-"$(basename "$file")"}
+    run cp "${ressources_dir}/${file}" "${source_dir}/${prefix}/$(dirname "$file")/${name}"
+}
+
+##############################################################################
+# @brief Creates a project using the basisproject command-line tool.
+create ()
+{
+    echo "Creating test project..."
+    [ -d "${source_dir}" ] && run rm -rf "${source_dir}"
+    run "${basisproject_path}" --name 'TestUtilities' --description "A project used to test the BASIS utilities." --root "${source_dir}" "$@"
+    echo "Creating test project... - done"
+}
+
+##############################################################################
+# @brief Tries to build a project created by basisproject.
+build ()
+{
+    local cwd="$(pwd)"
+    readonly cwd
+
+    echo "Configuring test project..."
+    [ -d "${binary_dir}" ] && run rm -rf "${binary_dir}"
+    run mkdir -p "${binary_dir}"
+    run cd "${binary_dir}"
+    run cmake "-DBASIS_DIR=${basis_dir}" "${source_dir}"
+    echo "Configuring test project... - done"
+    echo "Building test project..."
+    run make
+    echo "Building test project... - done"
+
+    run cd "${cwd}"
+}
+
+##############################################################################
+# @brief Cleanup source and binary tree.
+cleanup ()
+{
+    [ -d "${source_dir}" ] && run rm -rf "${source_dir}"
+    [ -d "${binary_dir}" ] && run rm -rf "${binary_dir}"
 }
 
 # ============================================================================
@@ -58,16 +138,11 @@ run ()
 # main
 # ============================================================================
 
-# ----------------------------------------------------------------------------
 # build tests
-if [ -d ${binary_dir} ]; then
-    run rm -rf "${binary_dir}"
-fi
-run mkdir -p "${binary_dir}"
-run cd "${binary_dir}"
-run cmake "-DBASIS_DIR=${basis_dir}" "${source_dir}"
-run make
+create
+build
 
-# ----------------------------------------------------------------------------
 # run tests
 
+# clean up
+cleanup
