Revised build of script files. @NAME@ patterns are replaced immediately while %NAME% patterns are replaced during the build step using the script configuration. Moved documentation from header of ScriptConfig.cmake.in file to separate Doxygen page.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@1292 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/tools/basistest-cron.sh.in b/src/tools/basistest-cron.sh.in
--- a/src/tools/basistest-cron.sh.in
+++ b/src/tools/basistest-cron.sh.in
@@ -29,8 +29,8 @@
 # constants
 # ============================================================================
 
-get_executable_directory EXEC_DIR  && readonly EXEC_DIR
-get_executable_name      EXEC_NAME && readonly EXEC_NAME
+get_executable_directory _EXEC_DIR  && readonly _EXEC_DIR
+get_executable_name      _EXEC_NAME && readonly _EXEC_NAME
 
 # ============================================================================
 # settings
@@ -61,13 +61,13 @@ schedule='/sbia/home/swtest/var/run/basistest.schedule'
 #
 # Has to be given with full path because SGE copies the slave script which
 # looks for the CTest script relative to its own location.
-ctest="${EXEC_DIR}/@MODULES_DIR@/basistest.ctest"
+ctest="${_EXEC_DIR}/%MODULES_DIR%/basistest.ctest"
 
 ## @brief Testing master script.
-master="${EXEC_DIR}/basistest-master"
+master="${_EXEC_DIR}/basistest-master"
 
 ## @brief Test execution command.
-slave="${EXEC_DIR}/basistest-slave -v -S ${ctest} --args shared-source,common-site=sbia-c5,common-site=compute"
+slave="${_EXEC_DIR}/basistest-slave -v -S ${ctest} --args shared-source,common-site=sbia-c5,common-site=compute"
 
 # ============================================================================
 # main
@@ -76,10 +76,8 @@ slave="${EXEC_DIR}/basistest-slave -v -S ${ctest} --args shared-source,common-si
 while [ $# -gt 0 ]; do
     case "$1" in
         -h|--help)
-            echo "@NAME@ (@PROJECT_NAME@)"
-            echo
             echo "Usage:"
-            echo "  ${EXEC_NAME}"
+            echo "  ${_EXEC_NAME}"
             echo
             echo "Description:"
             echo "  This command should be run regularly by a cron job. It contains"
@@ -91,22 +89,20 @@ while [ $# -gt 0 ]; do
             ;;
 
         --helpshort)
-            echo "@NAME@ (@PROJECT_NAME@)"
-            echo
             echo "Usage:"
-            echo "  ${EXEC_NAME}"
+            echo "  ${_EXEC_NAME}"
             echo
             print_contact
             exit 0
             ;;
 
         --version)
-            print_version '@NAME@'
+            print_version '%NAME%'
             exit 0
             ;;
 
         *)
-            echo "Invalid argument $1! See ${EXEC_NAME} --help." 1>&2
+            echo "Invalid argument $1! See ${_EXEC_NAME} --help." 1>&2
             exit 1
             ;;
     esac
diff --git a/src/tools/basistest.sh.in b/src/tools/basistest.sh.in
--- a/src/tools/basistest.sh.in
+++ b/src/tools/basistest.sh.in
@@ -15,8 +15,8 @@
 # constants
 # ============================================================================
 
-get_executable_name      EXEC_NAME && readonly EXEC_NAME
-get_executable_directory EXEC_DIR  && readonly EXEC_DIR
+get_executable_name      _EXEC_NAME && readonly _EXEC_NAME
+get_executable_directory _EXEC_DIR  && readonly _EXEC_DIR
 
 # ============================================================================
 # help
@@ -26,8 +26,6 @@ get_executable_directory EXEC_DIR  && readonly EXEC_DIR
 ## @brief Print help.
 function print_help
 {
-    echo "${EXEC_NAME} (@PROJECT_NAME@)"
-    echo
     print_synopsis
     echo
     cat - << EOF-DESCRIPTION
@@ -45,8 +43,6 @@ EOF-DESCRIPTION
 ## @brief Print usage information.
 function print_helpshort
 {
-    echo "${EXEC_NAME} (@PROJECT_NAME@)"
-    echo
     print_synopsis
     echo
     print_options
@@ -60,9 +56,9 @@ function print_synopsis
 {
     cat - << EOF-SYNOPSIS
 Usage:
-  ${EXEC_NAME} <cmd> [options] [options of subcommand]
-  ${EXEC_NAME} help <cmd>
-  ${EXEC_NAME} [options]
+  ${_EXEC_NAME} <cmd> [options] [options of subcommand]
+  ${_EXEC_NAME} help <cmd>
+  ${_EXEC_NAME} [options]
 EOF-SYNOPSIS
 }
 
@@ -105,11 +101,11 @@ if [ -n "$1" ]; then
                 exit 1
             fi
         else
-            echo "Missing subcommand! See ${EXEC_NAME} --help." 1>&2
+            echo "Missing subcommand! See ${_EXEC_NAME} --help." 1>&2
             exit 1
         fi
 
-        exec "${EXEC_DIR}/basistest-${cmd}" '--help'
+        exec "${_EXEC_DIR}/basistest-${cmd}" '--help'
     elif [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
         print_help
         exit 0
@@ -117,7 +113,7 @@ if [ -n "$1" ]; then
         print_helpshort
         exit 0
     elif [ "$1" == "--version" ]; then
-        print_version '@NAME@'
+        print_version '%NAME%'
         exit 0
     fi
 fi
@@ -126,5 +122,5 @@ fi
 # main
 # ============================================================================
 
-[ -n "${cmd}" ] || { echo "Missing subcommand! See ${EXEC_NAME} --help."; exit 1; }
-exec "${EXEC_DIR}/basistest-${cmd}" "$@"
+[ -n "${cmd}" ] || { echo "Missing subcommand! See ${_EXEC_NAME} --help."; exit 1; }
+exec "${_EXEC_DIR}/basistest-${cmd}" "$@"
