Minor change of error message.
git-svn-id: https://sbia-svn.uphs.upenn.edu/projects/BASIS/trunk@1807 3c61e6fb-ae43-4039-8cf7-c895b3257837

diff --git a/src/tools/basistest-slave.sh.in b/src/tools/basistest-slave.sh.in
--- a/src/tools/basistest-slave.sh.in
+++ b/src/tools/basistest-slave.sh.in
@@ -210,8 +210,12 @@ while [ $# -gt 0 ]; do
         # pass all unknown options as arguments to the CTest script
         *)
             if [ "${1:0:2}" != '--' ]; then
-                echo "Invalid argument: $1" 1>&2
-                echo "Did you mean --$1 instead?" 1>&2
+                if [ "${1:0:1}" == '-' ]; then
+                    echo "Invalid option: $1" 1>&2
+                else
+                    echo "Invalid argument: $1" 1>&2
+                    echo "Did you mean --$1 instead?" 1>&2
+                fi
                 exit 1
             fi
             add_arg "${1:2}"
